### ISSUE TITLE
Adding a Predicate

### ISSUE THREAD

**Issue by AdrianBinDC** [Whiffer/SampleSectionedQuery#1]
I'm attempting to swap out `@Query` in SwiftUI for `@SectionedQuery`. It works beautifully without a predicate, but I can't figure out how to add a predicate which updates in response to `searchTerm`

```swift
    @State private var searchTerm = ""

    @SectionedQuery(sectionIdentifier: \MyObject.id ,
                        sortDescriptors: [
        SortDescriptor(\MyObject.property1),
        SortDescriptor(\ MyObject.property2)
    ],
           animation: .smooth
    )
    var sections

    // stuff

    List {
        // my list consuming sections
    }
    .searchable(text: $searchTerm)
```

**Comment by AdrianBinDC** [comment]
Figured it out!

```swift
List {
    // list code
}
.onChange(of: searchTerm) {
    togglePredicate()
}

@MainActor
func togglePredicate() {
    guard !searchTerm.isEmpty else {
        sections.predicate = nil
        return
    }

    sections.predicate = #Predicate<MyThing> {
        $0.someProperty.localizedStandardContains(searchTerm)
    }
}

```

**Comment by Whiffer** [comment]
Adrian, thanks for the feedback.  I had already started preparing to add this function to the demo project for you when you posted your solution.  I will commit my update soon.

BTW, I was surprised to see that the #Predicate macro gets a compile error when prepending "self." to searchTerm in the call to Contains().  Am I missing something or does this seem to be a bug in the #Predicate macro?

FYI, you also left off the '0' after the '$' in your comment.

Thanks again.
